### ISSUE TITLE
Disable default-features for proc-macro-error

### ISSUE THREAD

**Issue by blorbb** [Kyuuhachi/syn_derive#2]
Hi!

Some context: I'm working on trying to remove all syn v1.* dependencies from [leptos](https://github.com/leptos-rs/leptos). I have gotten most of it done, but leptos depends on [rstml](https://github.com/rs-tml/rstml), which also depends on this crate.

proc-macro-error appears to no longer be maintained (>1y with no updates, not responding to issues). It is still using syn v1, however only for a single trait extension. This dependency on syn 1 can be disabled by removing the default feature `syn-error`. This feature can't even be used by crates using syn v2, so removing this feature should require no other changes to the code.

Could you disable default features on proc-macro-error to remove the unnecessary syn v1 dependency? This should also be a simple patch release. Change Cargo.toml to `proc-macro-error = { version = "1.0", default-features = false }`. 

Thanks!

**Comment by Kyuuhachi** [comment]
Sure, no problem. Didn't know that was a thing.
